- id: '1644989034775'
  alias: Tire Pressure Low
  description: ''
  trigger:
  - type: pressure
    platform: device
    device_id: e4f14c914bcebced798f3009924be84e
    entity_id: sensor.promaster_tpms_b1_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 9db4d7f3ba6ebdb304f5d44553ca71c3
    entity_id: sensor.promaster_tpms_b2_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 88e3d2e2a14e21e12cadc9748d815445
    entity_id: sensor.promaster_tpms_b3_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 4214db4df3d0c354cf8fc17e52ad3cb5
    entity_id: sensor.promaster_tpms_f1_tire_p_psi
    domain: sensor
    below: 58
  - type: pressure
    platform: device
    device_id: 123dc5a46a18fb1c10880427f4a2902c
    entity_id: sensor.promaster_tpms_f2_tire_p_psi
    domain: sensor
    below: 58
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data_template:
      message: '{{ trigger.entity.name }}'
      title: Tire Pressure is getting low
  mode: single
- id: '1645564536565'
  alias: Notify if there is a leak
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 292f4dcdbd21e23dfbba1ed9fee9d651
    entity_id: binary_sensor.water_leak_sensor_water_leak
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      message: Water sensor is wet!
      title: Warning
  mode: single
- id: '1647483395473'
  alias: Remote - Inverter On
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: brightness_up_hold
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: '1647483394123'
  alias: Remote - Inverter Off
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: brightness_down_hold
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.inverter
  mode: single
- id: 164748339432A
  alias: Remote - Inverter Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: toggle
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: 164748339547B
  alias: Remote - Inverter On
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_front_action
    to: brightness_up_hold
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: 1647483394123D
  alias: Remote - Inverter Off
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_front_action
    to: brightness_down_hold
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: 164748339432C
  alias: Remote - Inverter Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_front_action
    to: toggle
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
