- id: '1644989034775'
  alias: Notify Phone if Tire Pressure is low
  description: ''
  trigger:
  - type: pressure
    platform: device
    device_id: e4f14c914bcebced798f3009924be84e
    entity_id: sensor.promaster_tpms_b1_tire_spare_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 9db4d7f3ba6ebdb304f5d44553ca71c3
    entity_id: sensor.promaster_tpms_b2_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 88e3d2e2a14e21e12cadc9748d815445
    entity_id: sensor.promaster_tpms_b3_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 4214db4df3d0c354cf8fc17e52ad3cb5
    entity_id: sensor.promaster_tpms_f1_tire_p_psi
    domain: sensor
    below: 57
  - type: pressure
    platform: device
    device_id: 123dc5a46a18fb1c10880427f4a2902c
    entity_id: sensor.promaster_tpms_f2_tire_p_psi
    domain: sensor
    below: 57
  - platform: numeric_state
    entity_id: sensor.promaster_tpms_b2_tire_p_psi
    below: 75
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      title: Tire Pressure is getting low!
      message: '{{ trigger.entity_id }}, Date {{ now().strftime(''%Y-%m-%d'') }},
        Time {{ now().strftime(''%H:%M'') }}'
  mode: single
- id: '1645564536565'
  alias: Notify if there is a leak
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 292f4dcdbd21e23dfbba1ed9fee9d651
    entity_id: binary_sensor.water_leak_sensor_water_leak
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      message: Water sensor is wet!
      title: Warning
  mode: single
- id: '1647483395473'
  alias: Lights on back
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: brightness_up_hold
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 7
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1647483394123'
  alias: Lights off back
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: brightness_down_hold
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 7
    target:
      entity_id:
      - light.bed_light_matt
      - light.bed_light_chelsea
      - light.hallway_light
  mode: single
- id: 164748339432Af
  alias: Remote - Inverter Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: toggle
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: '1651985254516'
  alias: Matt lights up
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: arrow_right_click
    discovery_id: 0x2c1165fffecaf002 action_arrow_right_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step: 25
    target:
      entity_id: light.bed_light_matt
  mode: single
- id: '1651985340389'
  alias: Matt Light Down
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: arrow_left_click
    discovery_id: 0x2c1165fffecaf002 action_arrow_left_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step: -25
    target:
      entity_id: light.bed_light_matt
  mode: single
- id: '1652164968945'
  alias: Lights Full
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.lights_full
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 255
    target:
      entity_id:
      - light.hallway_light
      - light.bed_light_matt
      - light.bed_light_chelsea
  mode: single
- id: '1652165079553'
  alias: Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.lights_off
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1652888665810'
  alias: Notify Test
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      message: Sunset!
  mode: single
- id: '1669434786917'
  alias: Inverter Timer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.inverter_timer
    from: 'off'
    to: 'on'
    id: inverter-timer-on
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.inverter_timer
    id: inverter-timer-finished
  - platform: state
    entity_id:
    - input_boolean.inverter_timer
    from: 'on'
    to: 'off'
    id: inverter-timer-off
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: inverter-timer-on
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.inverter
      - service: timer.start
        data: {}
        target:
          entity_id: timer.inverter_timer
    - conditions:
      - condition: trigger
        id: inverter-timer-off
      sequence:
      - service: timer.pause
        data: {}
        target:
          entity_id: timer.inverter_timer
      - service: timer.cancel
        data: {}
        target:
          entity_id: timer.inverter_timer
    - conditions:
      - condition: trigger
        id: inverter-timer-finished
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.inverter
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.inverter_timer
  mode: single
- id: '1669436419986'
  alias: Adjust Heater Temperature Schedule
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
    alias: Midnight
    id: midnight
  - platform: time
    at: 06:50:00
    alias: Morning
    id: morning
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: midnight
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 55
        target:
          entity_id: climate.van_heating
    - conditions:
      - condition: trigger
        id: morning
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 66
        target:
          entity_id: climate.van_heating
  mode: single
- id: '1673932993939'
  alias: 1 Slowly dim lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.start_slow_dim
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: '{{ states(''input_number.light_dim_time'') | int(0) }}'
      brightness_pct: '{{ states(''input_number.dim_light_to'') | int(0) }}'
    target:
      entity_id:
      - light.front_light
      - light.bed_light_matt
      - light.hallway_light
      - light.bed_light_chelsea
  mode: single
- id: '1675839756900'
  alias: Chelsea IKEA buttons
  description: ''
  use_blueprint:
    path: malorezzanzo64/z2m-ikea-tradfri-5-button-remote-double-and-triple-clicks.yaml
    input:
      remote: sensor.remote_back_action
      button_center_x1:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.inverter
      button_center_x1_immediate: []
      button_center_x2:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.inverter_timer
      button_left_x1:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bed_light_chelsea
      button_center_x3:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.hallway_light
      button_right_x1:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bed_light_matt
      button_left_x2:
      - service: light.turn_on
        data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_chelsea
      button_left_x3:
      - service: light.turn_on
        data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_chelsea
      button_right_x2:
      - service: light.turn_on
        data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_matt
      button_right_x3:
      - service: light.turn_on
        data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_matt
      button_up_x1:
      - service: light.turn_on
        data:
          brightness_step_pct: 20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
      button_down_x1:
      - service: light.turn_on
        data:
          brightness_step_pct: -20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
      button_up_x2:
      - service: scene.turn_on
        target:
          entity_id: scene.dim_lights
        metadata: {}
      button_up_x3:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_on_full_3
        metadata: {}
      button_down_x2:
      - service: scene.turn_on
        target:
          entity_id: scene.very_dim
        metadata: {}
      button_down_x3:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off_3
        metadata: {}
- id: '1675897172627'
  alias: IKEA Matt
  description: ''
  use_blueprint:
    path: malorezzanzo64/z2m-ikea-tradfri-5-button-remote-double-and-triple-clicks.yaml
    input:
      remote: sensor.remote_front_action
      button_center_x1:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.inverter
      button_center_x1_immediate: []
      button_center_x2:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.inverter_timer
      button_left_x1:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bed_light_chelsea
      button_center_x3:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.hallway_light
      button_right_x1:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.bed_light_matt
      button_left_x2:
      - service: light.turn_on
        data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_chelsea
      button_left_x3:
      - service: light.turn_on
        data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_chelsea
      button_right_x2:
      - service: light.turn_on
        data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_matt
      button_right_x3:
      - service: light.turn_on
        data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_matt
      button_up_x1:
      - service: light.turn_on
        data:
          brightness_step_pct: 20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
      button_down_x1:
      - service: light.turn_on
        data:
          brightness_step_pct: -20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
      button_up_x2:
      - service: scene.turn_on
        target:
          entity_id: scene.dim_lights
        metadata: {}
      button_up_x3:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_on_full_3
        metadata: {}
      button_down_x2:
      - service: scene.turn_on
        target:
          entity_id: scene.very_dim
        metadata: {}
      button_down_x3:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off_3
        metadata: {}
- id: '1676523772368'
  alias: 11 Turn on inverter in the AM
  description: ''
  trigger:
  - platform: time
    at: 05:20:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: '1700699675793'
  alias: Button Lights
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 0bb108fd3aa04e6039041b4bfa00cca0
    type: action
    subtype: single
    discovery_id: 0xa4c138dfefa1a393 action_single
    id: Single
  - platform: device
    domain: mqtt
    device_id: 0bb108fd3aa04e6039041b4bfa00cca0
    type: action
    subtype: double
    discovery_id: 0xa4c138dfefa1a393 action_double
    id: Double
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Single
      sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_on_full_3
        metadata: {}
    - conditions:
      - condition: trigger
        id:
        - Double
      sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.lights_off_3
        metadata: {}
  mode: single
- id: '1707177604331'
  alias: Motion Lights based on time of day
  description: ''
  use_blueprint:
    path: Aleks130699/motion_light_brightness.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_occupancy
      light_target:
        entity_id: light.front_light
      no_motion_wait_night: 90
      on_night_time: '21:00:00'
      off_night_time: 08:55:00
      day_brightness: 100
      night_brightness: 10
      no_motion_wait_day: 600
