- id: '1644989034775'
  alias: Notify Phone if Tire Pressure is low
  description: ''
  trigger:
  - type: pressure
    platform: device
    device_id: e4f14c914bcebced798f3009924be84e
    entity_id: sensor.promaster_tpms_b1_tire_spare_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 9db4d7f3ba6ebdb304f5d44553ca71c3
    entity_id: sensor.promaster_tpms_b2_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 88e3d2e2a14e21e12cadc9748d815445
    entity_id: sensor.promaster_tpms_b3_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 4214db4df3d0c354cf8fc17e52ad3cb5
    entity_id: sensor.promaster_tpms_f1_tire_p_psi
    domain: sensor
    below: 57
  - type: pressure
    platform: device
    device_id: 123dc5a46a18fb1c10880427f4a2902c
    entity_id: sensor.promaster_tpms_f2_tire_p_psi
    domain: sensor
    below: 57
  - platform: numeric_state
    entity_id: sensor.promaster_tpms_b2_tire_p_psi
    below: 75
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone_s22
    data:
      title: Tire Pressure is getting low!
      message: '{{ trigger.entity_id }}, Date {{ now().strftime(''%Y-%m-%d'') }},
        Time {{ now().strftime(''%H:%M'') }}'
  mode: single
- id: '1645564536565'
  alias: Notify if there is a leak
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 292f4dcdbd21e23dfbba1ed9fee9d651
    entity_id: binary_sensor.water_leak_sensor_water_leak
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone_s22
    data:
      message: Water sensor is wet!
      title: Warning
  mode: single
- id: '1652888665810'
  alias: Notify Test
  description: ''
  triggers:
  - event: sunset
    offset: 0
    trigger: sun
  conditions: []
  actions:
  - action: notify.mobile_app_matt_s_phone_s22
    data: {}
  mode: single
- id: '1669434786917'
  alias: Set inverter timer to auto turn off inverter
  description: 'Turns on the inverter if it is not already on. Then it starts a 30-minute
    timer. When the timer runs out, it will turn the inverter off. '
  triggers:
  - entity_id:
    - input_boolean.inverter_timer
    from: 'off'
    to: 'on'
    id: inverter-timer-on
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.inverter_timer
    id: inverter-timer-finished
    trigger: event
  - entity_id:
    - input_boolean.inverter_timer
    from: 'on'
    to: 'off'
    id: inverter-timer-off
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: inverter-timer-on
      sequence:
      - data: {}
        target:
          entity_id:
          - switch.inverter_switch
        action: switch.turn_on
      - data: {}
        target:
          entity_id: timer.inverter_timer
        action: timer.start
    - conditions:
      - condition: trigger
        id: inverter-timer-off
      sequence:
      - data: {}
        target:
          entity_id: timer.inverter_timer
        action: timer.pause
      - data: {}
        target:
          entity_id: timer.inverter_timer
        action: timer.cancel
    - conditions:
      - condition: trigger
        id: inverter-timer-finished
      sequence:
      - data: {}
        target:
          entity_id:
          - switch.inverter_switch
        action: switch.turn_off
      - data: {}
        target:
          entity_id: input_boolean.inverter_timer
        action: input_boolean.toggle
  mode: single
- id: '1669436419986'
  alias: Adjust Heater Temperature Schedule
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
    alias: Midnight
    id: midnight
  - platform: time
    at: 06:50:00
    alias: Morning
    id: morning
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: midnight
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 55
        target:
          entity_id: climate.van_heating
    - conditions:
      - condition: trigger
        id: morning
      sequence:
      - service: climate.set_temperature
        data:
          temperature: 66
        target:
          entity_id: climate.van_heating
  mode: single
- id: '1673932993939'
  alias: 1 Slowly dim lights
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.start_slow_dim
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: '{{ states(''input_number.light_dim_time'') | int(0) }}'
      brightness_pct: '{{ states(''input_number.dim_light_to'') | int(0) }}'
    target:
      entity_id:
      - light.front_light
      - light.bed_light_matt
      - light.hallway_light
      - light.bed_light_chelsea
  mode: single
- id: '1675839756900'
  alias: Chelsea IKEA buttons
  description: ''
  use_blueprint:
    path: malorezzanzo64/z2m-ikea-tradfri-5-button-remote-double-and-triple-clicks.yaml
    input:
      remote: sensor.remote_back_action
      button_center_x1:
      - data: {}
        target:
          entity_id: switch.inverter
        action: switch.toggle
      button_center_x1_immediate: []
      button_center_x2:
      - data: {}
        target:
          entity_id: input_boolean.inverter_timer
        action: input_boolean.toggle
      button_left_x1:
      - data: {}
        target:
          entity_id: light.bed_light_chelsea
        action: light.toggle
      button_center_x3:
      - data: {}
        target:
          entity_id: light.hallway_light
        action: light.toggle
      button_right_x1:
      - data: {}
        target:
          entity_id: light.bed_light_matt
        action: light.toggle
      button_left_x2:
      - data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_chelsea
        action: light.turn_on
      button_left_x3:
      - data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_chelsea
        action: light.turn_on
      button_right_x2:
      - data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_matt
        action: light.turn_on
      button_right_x3:
      - data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_matt
        action: light.turn_on
      button_up_x1:
      - data:
          brightness_step_pct: 20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
          - light.front_light
        action: light.turn_on
      button_down_x1:
      - data:
          brightness_step_pct: -20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
          - light.front_light
        action: light.turn_on
      button_up_x2:
      - target:
          entity_id: scene.dim_lights
        metadata: {}
        action: scene.turn_on
      button_up_x3:
      - target:
          entity_id: scene.lights_on_full_3
        metadata: {}
        action: scene.turn_on
      button_down_x2:
      - target:
          entity_id: scene.very_dim
        metadata: {}
        action: scene.turn_on
      button_down_x3:
      - target:
          entity_id: scene.lights_off_3
        metadata: {}
        action: scene.turn_on
- id: '1676523772368'
  alias: Turn on inverter in the AM
  description: Every morning, turn the inverter on at a certain time. This is designed
    to turn on starlink before I wake up so it has time to boot.
  triggers:
  - at: 05:20:00
    trigger: time
  conditions: []
  actions:
  - data: {}
    target:
      entity_id:
      - switch.inverter_switch
    action: switch.turn_on
  mode: single
- id: '1700699675793'
  alias: Front Button Lights
  description: 'Single Press - All on

    Double Press - All off'
  triggers:
  - domain: mqtt
    device_id: 0bb108fd3aa04e6039041b4bfa00cca0
    type: action
    subtype: single
    discovery_id: 0xa4c138dfefa1a393 action_single
    id: Single
    trigger: device
  - domain: mqtt
    device_id: 0bb108fd3aa04e6039041b4bfa00cca0
    type: action
    subtype: double
    discovery_id: 0xa4c138dfefa1a393 action_double
    id: Double
    trigger: device
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Single
      sequence:
      - target:
          entity_id: scene.lights_on_full_3
        metadata: {}
        action: scene.turn_on
    - conditions:
      - condition: trigger
        id:
        - Double
      sequence:
      - target:
          entity_id: scene.lights_off_3
        metadata: {}
        action: scene.turn_on
  mode: single
- id: '1707177604331'
  alias: Motion Lights based on time of day
  description: ''
  use_blueprint:
    path: Aleks130699/motion_light_brightness.yaml
    input:
      motion_entity: binary_sensor.motion_sensor_occupancy
      light_target:
        entity_id: light.front_light
      no_motion_wait_night: 90
      on_night_time: '21:00:00'
      off_night_time: 08:55:00
      day_brightness: 100
      night_brightness: 10
      no_motion_wait_day: 600
- id: '1731909849425'
  alias: BOOT  - Start Z2M after boot
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - action: hassio.addon_start
    metadata: {}
    data:
      addon: 45df7312_zigbee2mqtt
  mode: single
- id: '1731913833397'
  alias: Matt IKEA Remote
  description: ''
  use_blueprint:
    path: malorezzanzo64/z2m-ikea-tradfri-5-button-remote-double-and-triple-clicks.yaml
    input:
      remote: sensor.remote_front_action
      button_center_x1:
      - data: {}
        target:
          entity_id: switch.inverter
        action: switch.toggle
      button_center_x1_immediate: []
      button_center_x2:
      - data: {}
        target:
          entity_id: input_boolean.inverter_timer
        action: input_boolean.toggle
      button_left_x1:
      - data: {}
        target:
          entity_id: light.bed_light_chelsea
        action: light.toggle
      button_center_x3:
      - data: {}
        target:
          entity_id: light.hallway_light
        action: light.toggle
      button_right_x1:
      - data: {}
        target:
          entity_id: light.bed_light_matt
        action: light.toggle
      button_left_x2:
      - data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_chelsea
        action: light.turn_on
      button_left_x3:
      - data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_chelsea
        action: light.turn_on
      button_right_x2:
      - data:
          brightness_step_pct: 34
        target:
          entity_id: light.bed_light_matt
        action: light.turn_on
      button_right_x3:
      - data:
          brightness_step_pct: -34
        target:
          entity_id: light.bed_light_matt
        action: light.turn_on
      button_up_x1:
      - data:
          brightness_step_pct: 20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
          - light.front_light
        action: light.turn_on
      button_down_x1:
      - data:
          brightness_step_pct: -20
        target:
          entity_id:
          - light.bed_light_chelsea
          - light.bed_light_matt
          - light.hallway_light
          - light.front_light
        action: light.turn_on
      button_up_x2:
      - target:
          entity_id: scene.dim_lights
        metadata: {}
        action: scene.turn_on
      button_up_x3:
      - target:
          entity_id: scene.lights_on_full_3
        metadata: {}
        action: scene.turn_on
      button_down_x2:
      - target:
          entity_id: scene.very_dim
        metadata: {}
        action: scene.turn_on
      button_down_x3:
      - target:
          entity_id: scene.lights_off_3
        metadata: {}
        action: scene.turn_on
- id: '1731972220945'
  alias: BOOT - Refresh MQTT Victron on boot
  description: Request the data on the MQTT server
  triggers:
  - event: start
    trigger: homeassistant
  conditions: []
  actions:
  - data:
      topic: venus-home/R/b827ebb94e80/system/0/Serial
    action: mqtt.publish
  mode: single
