- id: '1644989034775'
  alias: Notify Phone if Tire Pressure is low
  description: ''
  trigger:
  - type: pressure
    platform: device
    device_id: e4f14c914bcebced798f3009924be84e
    entity_id: sensor.promaster_tpms_b1_tire_spare_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 9db4d7f3ba6ebdb304f5d44553ca71c3
    entity_id: sensor.promaster_tpms_b2_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 88e3d2e2a14e21e12cadc9748d815445
    entity_id: sensor.promaster_tpms_b3_tire_p_psi
    domain: sensor
    below: 65
  - type: pressure
    platform: device
    device_id: 4214db4df3d0c354cf8fc17e52ad3cb5
    entity_id: sensor.promaster_tpms_f1_tire_p_psi
    domain: sensor
    below: 58
  - type: pressure
    platform: device
    device_id: 123dc5a46a18fb1c10880427f4a2902c
    entity_id: sensor.promaster_tpms_f2_tire_p_psi
    domain: sensor
    below: 58
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      title: Tire Pressure is getting low!
      message: Check tire pressure
  mode: single
- id: '1645564536565'
  alias: Notify if there is a leak
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 292f4dcdbd21e23dfbba1ed9fee9d651
    entity_id: binary_sensor.water_leak_sensor_water_leak
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      message: Water sensor is wet!
      title: Warning
  mode: single
- id: '1647483395473'
  alias: Lights on back
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: brightness_up_hold
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 7
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1647483394123'
  alias: Lights off back
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: brightness_down_hold
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 7
    target:
      entity_id:
      - light.bed_light_matt
      - light.bed_light_chelsea
      - light.hallway_light
  mode: single
- id: 164748339432Af
  alias: Remote - Inverter Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_back_action
    to: toggle
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: 164748339547B
  alias: Lights on front
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_front_action
    to: brightness_up_hold
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: 1647483394123D
  alias: Lights off front remote
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.remote_front_action
    to: brightness_down_hold
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 5
    target:
      entity_id:
      - light.bed_light_matt
      - light.bed_light_chelsea
      - light.hallway_light
  mode: single
- id: 164748339432CH
  alias: Remote - Inverter Toggle
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: toggle
    discovery_id: 0x2c1165fffecaf002 action_toggle
  condition: []
  action:
  - service: input_button.press
    data: {}
    target:
      entity_id: input_button.ikea_center
  mode: single
- id: '1648440424322'
  alias: button to phone
  description: ''
  use_blueprint:
    path: vorion/actionable-notifications-for-android.yaml
    input:
      notify_device: 5645c1b64d18128e58fdf8d9d69dde22
      notification_title: Testing
      notification_message: Testing 123
      action_1_title: Button 1
      first_action:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.inverter
      trigger_entity: input_boolean.pushit
- id: '1648571899858'
  alias: IKEA Button Press
  description: ''
  trigger:
  - platform: state
    entity_id: input_button.ikea_center
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.inverter
  mode: single
- id: '1651984868811'
  alias: Chelsea lights up
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: brightness_up_click
    discovery_id: 0x2c1165fffecaf002 action_brightness_up_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step: 25
    target:
      entity_id: light.bed_light_chelsea
  mode: single
- id: '1651985045659'
  alias: Chelsea Lights Down
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: brightness_down_click
    discovery_id: 0x2c1165fffecaf002 action_brightness_down_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step: -25
    target:
      entity_id: light.bed_light_chelsea
  mode: single
- id: '1651985254516'
  alias: Matt lights up
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: arrow_right_click
    discovery_id: 0x2c1165fffecaf002 action_arrow_right_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step: 25
    target:
      entity_id: light.bed_light_matt
  mode: single
- id: '1651985340389'
  alias: Matt Light Down
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: arrow_left_click
    discovery_id: 0x2c1165fffecaf002 action_arrow_left_click
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step: -25
    target:
      entity_id: light.bed_light_matt
  mode: single
- id: '1651985481023'
  alias: Toggle All Lights
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 72016eb7fc7eb4e8b691eab072560377
    type: action
    subtype: toggle_hold
    discovery_id: 0x2c1165fffecaf002 action_toggle_hold
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1652164968945'
  alias: Lights Full
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.lights_full
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 255
    target:
      entity_id:
      - light.hallway_light
      - light.bed_light_matt
      - light.bed_light_chelsea
  mode: single
- id: '1652165079553'
  alias: Lights Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.lights_off
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1652165140206'
  alias: Chelsea Light Dim Button
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.chelsea_light_dim
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 3
    target:
      entity_id: light.bed_light_chelsea
  mode: single
- id: '1652888665810'
  alias: Notify Test
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: notify.mobile_app_matt_s_phone
    data:
      message: Sunset!
  mode: single
- id: '1653437640540'
  alias: Wheel Light Decrease
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2af505a102de914e4b3fc1eb60cc6f5f
    type: action
    subtype: rotate_left
    discovery_id: 0xec1bbdfffe396b76 action_rotate_left
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: -5
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1653437946319'
  alias: Wheel Light Increase
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2af505a102de914e4b3fc1eb60cc6f5f
    type: action
    subtype: rotate_right
    discovery_id: 0xec1bbdfffe396b76 action_rotate_right
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 5
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1653438210449'
  alias: Wheel Spin
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.wheel_action
    attribute: brightness
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: '{{state_attr(''sensor.wheel_action'', ''brightness'')|int}}'
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: parallel
  max: 100
- id: '1653440818701'
  alias: Wheel Button
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2af505a102de914e4b3fc1eb60cc6f5f
    type: action
    subtype: play_pause
    discovery_id: 0xec1bbdfffe396b76 action_play_pause
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id:
      - light.bed_light_chelsea
      - light.bed_light_matt
      - light.hallway_light
  mode: single
- id: '1653440901275'
  alias: Wheel Double Tap
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2af505a102de914e4b3fc1eb60cc6f5f
    type: action
    subtype: skip_forward
    discovery_id: 0xec1bbdfffe396b76 action_skip_forward
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on_full_3
    metadata: {}
  mode: single
- id: '1653440935233'
  alias: Wheel Triple Tap
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 2af505a102de914e4b3fc1eb60cc6f5f
    type: action
    subtype: skip_backward
    discovery_id: 0xec1bbdfffe396b76 action_skip_backward
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.dim_lights
    metadata: {}
  mode: single
