# Switch to turn the heater on and off
- platform: mqtt
  name: Heater Thermostat On / Off
  state_topic: "AfterburnerD014E4/sts/Run"
  command_topic: "AfterburnerD014E4/JSONin"
  value_template: '{{ value }}'
  payload_on: '{"Run":1}'
  payload_off: '{"Run":0}'
  state_on: "1"
  state_off: "0"
  optimistic: false
  retain: false
  qos: 0
  icon: mdi:power