# Switch to turn the inverter on and off
# This one slightly works but is a little janky
- platform: mqtt
  name: Inverter On / Charge Only
#   state_topic: "venus-home/N/b827ebb94e80/vebus/288/Mode"
  command_topic: "venus-home/W/b827ebb94e80/vebus/288/Mode"
  value_template: '{{ value }}'  
  payload_on: '{"value":3}'
  payload_off: '{"value":1}'
#   state_on: '3'
#   state_off: '{"value":1}'
  optimistic: false
  retain: true
  qos: 0
  icon: mdi:power
