# Switch to turn the inverter on and off
- platform: mqtt
  name: Inverter
  state_topic: "venus-home/N/b827ebb94e80/vebus/289/Mode"
  command_topic: "venus-home/W/b827ebb94e80/vebus/289/Mode"
  value_template: '{{ value }}'
  payload_on: '{"value": 3}'
  payload_off: '{"value": 1}'
  optimistic: false
  retain: true
  qos: 0
  icon: mdi:power

# Switch to turn the inverter on and off
- platform: mqtt
  name: Charger
  state_topic: "venus-home/N/b827ebb94e80/vebus/289/Mode"
  command_topic: "venus-home/W/b827ebb94e80/vebus/289/Mode"
  value_template: '{{ value.value }}'
  payload_on: '{"value": 3}'
  payload_off: '{"value": 1}'
  # state_on: '3'
  # state_off: '1'
  optimistic: false
  retain: true
  qos: 0
  icon: mdi:power
