# Fridge over BLE to MQTT

#  Fridge temp
- name: "Fridge Temperature"
  unique_id: sensor_fridge_temperature
  state_topic: "fridge/temperature/fridge"
  unit_of_measurement: '°F'
  value_template: "{{ value }}"
  device_class: temperature
  state_class: measurement

#  Freezer temp
- name: "Freezer Temperature"
  unique_id: sensor_freezer_temperature
  state_topic: "fridge/temperature/freezer"
  unit_of_measurement: '°F'
  value_template: "{{ value }}"
  device_class: temperature
  state_class: measurement
