# Automation that gets run ever 30 seconds to request MQTT info
- id: '1643333678664'
  alias: Refresh MQTT Victron
  description: Request the data on the MQTT server
  trigger:
  - platform: time_pattern
    seconds: '30'
  action:
  - service: mqtt.publish
    data:
      topic: venus-home/R/b827ebb94e80/system/0/Serial
  mode: single

# This will set our "home" location to match the location of the keys
- id: '1644339090750'
  alias: Set Location
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition: []
  action:
  - service: homeassistant.set_location
    data_template:
      latitude: |
        {{ state_attr('device_tracker.keys_tile', 'latitude') }}
      longitude: |
        {{ state_attr('device_tracker.keys_tile', 'longitude') }}
  mode: single
