# This will set our "home" location to match the location of the keys
- id: 'Set location'
  alias: Set Location
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition: []
  action:
  - service: homeassistant.set_location
    data_template:
      latitude: |
        {{ state_attr('device_tracker.chelseas_purse_tile', 'latitude') }}
      longitude: |
        {{ state_attr('device_tracker.chelseas_purse_tile', 'longitude') }}
  mode: single
