
# Get battery info on boot
- id: 'RefreshVictronMQTT-30seconds'
  alias: Refresh MQTT Victron every 30 seconds
  description: Request the data on the MQTT server
  trigger:
  - platform: time_pattern
    seconds: '30'
  action:
  - service: mqtt.publish
    data:
      topic: venus-home/R/b827ebb94e80/system/0/Serial
  mode: single
