# HEATER entities

# Thermostat status
- platform: mqtt
  name: "Heater Thermostat Status"
  state_topic: "AfterburnerD014E4/status"
  availability:
    - topic: "AfterburnerD014E4/status"
  icon: mdi:thermostat

- platform: mqtt
  name: "Heater Thermostat Run 01"
  state_topic: "AfterburnerD014E4/stsRetained/Run"
  value_template: "{{ value }}"
  icon: mdi:state-machine

- platform: mqtt
  name: "Heater Thermostat Run State"
  state_topic: "AfterburnerD014E4/stsRetained/RunString"
  value_template: "{{ value }}"
  icon: mdi:state-machine

- platform: mqtt
  name: "Heater Current Temperature"
  state_topic: "AfterburnerD014E4/stsRetained/TempCurrent"
  unit_of_measurement: '째C'
  value_template: "{{ value }}"
  device_class: temperature
  state_class: measurement

- platform: mqtt
  name: "Heater Current Temperature Sensor 2"
  state_topic: "AfterburnerD014E4/stsRetained/Temp2Current"
  unit_of_measurement: '째C'
  value_template: "{{ value }}"
  device_class: temperature
  state_class: measurement

- platform: mqtt
  name: "Heater Current Temperature of Body"
  state_topic: "AfterburnerD014E4/stsRetained/TempBody"
  unit_of_measurement: '째C'
  value_template: "{{ value }}"
  device_class: temperature
  state_class: measurement

- platform: mqtt
  name: "Heater Desired Temperature"
  state_topic: "AfterburnerD014E4/stsRetained/TempDesired"
  unit_of_measurement: '째C'
  value_template: "{{ value }}"
  device_class: temperature
  state_class: measurement

- platform: mqtt
  name: "Heater Input Voltage"
  state_topic: "AfterburnerD014E4/stsRetained/InputVoltage"
  unit_of_measurement: 'V'
  value_template: "{{ value }}"
  icon: mdi:lightning-bolt
  device_class: voltage
  state_class: measurement

- platform: mqtt
  name: "Heater GlowPlug Voltage"
  state_topic: "AfterburnerD014E4/stsRetained/GlowVoltage"
  unit_of_measurement: 'V'
  value_template: "{{ value }}"
  icon: mdi:lightning-bolt
  device_class: voltage
  state_class: measurement

- platform: mqtt
  name: "Heater GlowPlug Current"
  state_topic: "AfterburnerD014E4/stsRetained/GlowCurrent"
  unit_of_measurement: 'A'
  value_template: "{{ value }}"
  device_class: current
  state_class: measurement

- platform: mqtt
  name: "Heater Fuel Usage"
  state_topic: "AfterburnerD014E4/stsRetained/FuelUsage"
  unit_of_measurement: 'mL'
  value_template: "{{ value }}"
  icon: mdi:fuel

- platform: mqtt
  name: "Heater Fuel Usage Total"
  state_topic: "AfterburnerD014E4/stsRetained/TotalFuelUsage"
  unit_of_measurement: 'mL'
  value_template: "{{ value }}"
  icon: mdi:fuel

- platform: mqtt
  name: "Heater Fuel Rate"
  state_topic: "AfterburnerD014E4/stsRetained/FuelRate"
  unit_of_measurement: 'mL/hr'
  value_template: "{{ value }}"
  icon: mdi:fuel

- platform: mqtt
  name: "Heater Fan Speed"
  state_topic: "AfterburnerD014E4/stsRetained/FanRPM"
  unit_of_measurement: 'RPM'
  value_template: "{{ value }}"
  icon: mdi:fan

- platform: mqtt
  state_topic: "AfterburnerD014E4/stsRetained/Humidity"
  name: 'Heater Relative Humidity'
  unit_of_measurement: '%'
  value_template: "{{ value }}"
  icon: mdi:water-percent
  device_class: humidity
  state_class: measurement

- platform: mqtt
  state_topic: "AfterburnerD014E4/stsRetained/Altitude"
  name: 'Heater Altitude'
  unit_of_measurement: 'ft'
  value_template: "{{ value | float(1) | round(1) }}"
  icon: mdi:terrain

- platform: mqtt
  state_topic: "AfterburnerD014E4/stsRetained/Pressure"
  name: 'Heater Pressure'
  unit_of_measurement: 'hPa'
  value_template: "{{ value }}"
  icon: mdi:weather-windy-variant
  device_class: pressure
  state_class: measurement

