# Victron Entities

#  Solar

- platform: mqtt
  name: "Solar Voltage"
  state_topic: "venus-home/N/b827ebb94e80/solarcharger/289/Pv/V"
  unit_of_measurement: 'V'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:solar-panel
  device_class: voltage

- platform: mqtt
  name: "Solar Current"
  state_topic: "venus-home/N/b827ebb94e80/solarcharger/289/Pv/I"
  unit_of_measurement: 'A'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:solar-power
  device_class: current
  
- platform: mqtt
  name: "Solar Power"
  state_topic: "venus-home/N/b827ebb94e80/system/0/Dc/Pv/Power"
  unit_of_measurement: 'W'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:solar-panel
  device_class: power

#  AC

- platform: mqtt
  name: "AC Loads"
  state_topic: "venus-home/N/b827ebb94e80/system/0/Ac/Consumption/L1/Power"
  unit_of_measurement: 'W'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:power-socket-us
  device_class: power

# This topic contains other things like F (hz), I (amps), V (volts)
# venus-home/N/b827ebb94e80/vebus/288/Ac/ActiveIn/#
- platform: mqtt
  name: "Shore Power In"
  state_topic: "venus-home/N/b827ebb94e80/vebus/288/Ac/ActiveIn/P"
  unit_of_measurement: 'W'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:power-plug
  device_class: power

# DC

- platform: mqtt
  name: "DC Loads"
  state_topic: "venus-home/N/b827ebb94e80/system/0/Dc/System/Power"
  unit_of_measurement: 'W'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:current-dc
  device_class: power

# Battery

- platform: mqtt
  name: "Total Power Usage"
  state_topic: "venus-home/N/b827ebb94e80/system/0/Dc/Battery/Power"
  unit_of_measurement: 'Watts'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:lightning-bolt
  device_class: power

- platform: mqtt
  name: "Battery SOC"
  state_topic: "venus-home/N/b827ebb94e80/system/0/Dc/Battery/Soc"
  unit_of_measurement: '%'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:battery-high
  device_class: battery

- platform: mqtt
  name: "Battery Voltage"
  state_topic: "venus-home/N/b827ebb94e80/system/0/Dc/Battery/Voltage"
  unit_of_measurement: 'V'
  value_template: "{{ value_json.value | float(0) | round(2) }}"
  icon: mdi:lightning-bolt
  device_class: voltage

- platform: mqtt
  name: "Battery Time Remaining"
  icon: mdi:battery-clock
  state_topic: "venus-home/N/b827ebb94e80/system/0/Dc/Battery/TimeToGo"
  value_template: >-
          {% if (value_json.value is defined) %}
            {% set time = value_json.value | int(-1) %}
          {% else %}
            {% set time = -2 %}
          {% endif %}
          {% set minutes = ((time % 3600) / 60) | int %}
          {% set hours = ((time % 86400) / 3600) | int %}
          {% set days = (time / 86400) | int %}

          {%- if time == -2 -%}
            Waiting for estimate
          {%- elif time == -1 -%}
            Infinite
          {%- elif time < 60 -%}
            Less than a minute
          {%- else -%}
            {%- if days > 0 -%}
              {%- if days == 1 -%}
                1 day
              {%- else -%}
                {{ days }} days
              {%- endif -%}
            {%- endif -%}
            {%- if hours > 0 -%}
              {%- if days > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if hours == 1 -%}
                1 hour
              {%- else -%}
                {{ hours }} hours
              {%- endif -%}
            {%- endif -%}
            {%- if minutes > 0 -%}
              {%- if days > 0 or hours > 0 -%}
                {{ ', ' }}
              {%- endif -%}
              {%- if minutes == 1 -%}
                1 minute
              {%- else -%}
                {{ minutes }} minutes
              {%- endif -%}
            {%- endif -%}
          {%- endif -%}