# Power Sums:

- platform: integration
  name: "Solar Power In"
  source: sensor.solar_power

- platform: integration
  name: "DC Loads Total"
  source: sensor.dc_loads

- platform: integration
  name: "Shore Power In Total"
  source: sensor.shore_power_in

- platform: integration
  name: "AC Loads Total"
  source: sensor.ac_loads