
# Switch to turn the heater on and off
- name: Heater Thermostat On / Off
  unique_id: sensor_heater_thermostat_on_off
  state_topic: "AfterburnerD014E4/stsRetained/Run"
  command_topic: "AfterburnerD014E4/JSONin"
  payload_on: '{"Run":1}'
  payload_off: '{"Run":0}'
  state_on: "1"
  state_off: "0"
  optimistic: false
  retain: false
  qos: 0
  icon: mdi:power