# Device tracker images for the map
device_tracker.keys_tile:
  entity_picture: "/local/key.png"

device_tracker.wallet_tile:
  entity_picture: "/local/wallet.png"

device_tracker.matts_phone_tile:
  entity_picture: "/local/samsung-galaxy.jpg"

# Van Icon Home
zone.home:
  icon: mdi:van-utility


#   # Customize all entities in a domain
#   customize_domain:
#     light:
#       icon: mdi:home
#     automation:
#       initial_state: "on"
#   # Customize entities matching a pattern
#   customize_glob:
#     "light.kitchen_*":
#       icon: mdi:description
#     "scene.month_*_colors":
#       icon: mdi:other