esphome:
  name: lights

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret lights_esp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lights Fallback Hotspot"
    password: !secret lights_esp_ap_fallback_password

captive_portal:

output:
  # Light 1
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 100 Hz
    id: pwm12
  # Light 2
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 100 Hz
    id: pwm14
  # Light 3
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 100 Hz
    id: pwm4
  # Light 4
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 100 Hz
    id: pwm5
    # Try this in the future to limit the range:
    # min_power: 0.01
    # max_power: 0.75
    # zero_means_zero: true

# Lights example
light:
  - platform: monochromatic
    name: "Light 1"
    output: pwm12
  - platform: monochromatic
    name: "Light 2"
    output: pwm14
  - platform: monochromatic
    name: "Light 3"
    output: pwm4
  - platform: monochromatic
    name: "Light 4"
    output: pwm5