esphome:
  name: lights

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: !secret lights_esp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lights Fallback Hotspot"
    password: !secret lights_esp_ap_fallback_password

captive_portal:

output:
  # Bed Light Matt
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 100 Hz
    id: pwm12
    min_power: 0.01
    zero_means_zero: true
  # Bed Light Chelsea
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 100 Hz
    id: pwm14
    min_power: 0.01
    zero_means_zero: true
  # Hallway Light
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 100 Hz
    id: pwm4
    min_power: 0.01
    zero_means_zero: true
  # Closet Light
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 100 Hz
    id: pwm5
    min_power: 0.01
    zero_means_zero: true

# Lights example
light:
  - platform: monochromatic
    name: "Bed Light Matt"
    output: pwm12
    id: bed_light_matt
  - platform: monochromatic
    name: "Bed Light Chelsea"
    output: pwm14
    id: bed_light_chelsea
  - platform: monochromatic
    name: "Hallway Light"
    output: pwm4
    id: hallway_light
  - platform: monochromatic
    name: "Front Light"
    output: pwm5
    id: front_light

web_server:
  port: 80

