# Your Wi-Fi SSID and password
wifi_ssid: ""
wifi_password: ""

# Air quality monitor:
aqm_esp_ap_fallback_password: ""
aqm_esp_ota_password: ""

# Lights:
lights_esp_ap_fallback_password: ""
lights_esp_ota_password: ""

